### ISSUE TITLE
Tag 0.2

### ISSUE THREAD

**Issue by Nyholm** [FriendsOfApi/localise.biz#11]
@sagikazarmark Do you have any comments or suggestions on this API client? 

It is not feature complete but I believe all best practices from the boilerplate is used.

**Comment by sagikazarmark** [comment]
One comment: if the models are mutable, why disabling the constructor? IMO the validation rules should all go to the constructor, and any kind of static constructing logic should eventually be translated to calling the object constructor.

**Comment by Nyholm** [comment]
Thank you for the review. The models are immutable. The setters are all private. 

You might be correct. That would make the models reusable.
