### ISSUE TITLE
Client does not support keys containing "spaces"

### ISSUE THREAD

**Issue by jkobus** [FriendsOfApi/localise.biz#19]
Keys like "submit button" are not supported. 
Translation asset is created (its sent in POST body), but when we try to add translation it fails:

Translation.php:62
`$response = $this->httpPostRaw(sprintf('/api/translations/%s/%s?key=%s', urlencode($id), $locale, $projectKey), $translation);`

this becomes:

`/api/translations/some translation key/pl?key=12`

Request that is actually beeing sent is directed to:

`/api/translations/some`

... and that results in an error response from api: "Missing API key"

This might be related to how the http client implementation handles such cases, I used the `php-http/curl-client`.

PR is on the way.

**Comment by Nyholm** [comment]
Fixed by #20
