### ISSUE TITLE
Looking for maintainer?

### ISSUE THREAD

**Issue by odolbeau** [FriendsOfApi/localise.biz#30]
Hi @Nyholm 

It looks like your lacking of time for maintaining this repository.
We didn't heard from you since February on #29.

If needed, I can help on this package.

For example, I'll be glad to work on a v2 based on `symfony/http-client`.
Is it something which is in your plan or should I create a dedicated fork?

Thanks in advance for your answer!

**Comment by Nyholm** [comment]
Hey. 

Thank you for reaching out. That would be great to have you as a maintainer. 

About `symfony/http-client`, Have you seen the [HTTPlug adapter](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpClient/HttplugClient.php)?

**Comment by odolbeau** [comment]
Thanks for the access! :+1: 

I saw this adapter but I'm pretty sure symfony/http-client will be widely used very fast and it's way simpler to use the httplug IMO.

Some stats right now:
* [397 packages](https://packagist.org/packages/php-http/httplug/dependents) depends on `php-http/httplug`
* [51 packages](https://packagist.org/packages/symfony/http-client/dependents) depends on `symfony/http-clients`.

Let's see how it evolves in the future, releasing a v2.0 is not a high priority anyway as this one works very well. :)

**Comment by Nyholm** [comment]
Yeah, and you also have to add these 150 packages that depends on `psr/http-client`: https://packagist.org/packages/psr/http-client

=)

**Comment by odolbeau** [comment]
Well, I guess we really have time before considering moving to `symfony/http-client`, let's forget it for now. :)
